// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/georg/Desktop/Uni stuff/React Native elective/Exam project/exam-project-myversion/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/georg/Desktop/Uni stuff/React Native elective/Exam project/exam-project-myversion/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('exam-project-myversion', appParameters);
});
require('c:/Users/georg/Desktop/Uni stuff/React Native elective/Exam project/exam-project-myversion/index.js');